// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 15.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.Ionic
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class AppView : AppBaseClass
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"<!--
  You should add your licence here, here is an example :

  SonarQube, open source software quality management tool.
  Copyright (C) 2008-2013 SonarSource
  mailto:contact AT sonarsource DOT com

  SonarQube is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 3 of the License, or (at your option) any later version.
 
  SonarQube is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.
 
  You should have received a copy of the GNU Lesser General Public License
  along with this program; if not, write to the Free Software Foundation,
  Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
-->
");
            
            #line 28 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

    SmartAppInfo smartApp = (SmartAppInfo)Model;
    if (smartApp != null && smartApp.Concerns.AsEnumerable() != null)
    {
      if (_isMenu)
      {

            
            #line default
            #line hidden
            this.Write("<ion-menu persistent=\"true\" [content]=\"nav\" side=\"left\">\r\n  <ion-content>\r\n    <i" +
                    "on-list>\r\n      <ion-item menuClose text-center>\r\n        <ion-icon name=\"ios-ar" +
                    "row-back\" float-left></ion-icon>\r\n");
            
            #line 40 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"
 
        if (smartApp.Languages.AsEnumerable() != null && smartApp.Languages.AsEnumerable().Count() > 0)
        {

            
            #line default
            #line hidden
            this.Write("          {{ \"closeMenu\" | translate }}\r\n");
            
            #line 45 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("          CloseMenu\r\n");
            
            #line 51 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

        }

            
            #line default
            #line hidden
            this.Write("      </ion-item>\r\n      <ion-item-group>\r\n        <a ion-item menuClose *ngFor=\"" +
                    "let m of _menu\" (click)=\"selected(m.component.toLowerCase())\">{{ m.name }}</a>\r\n" +
                    "      </ion-item-group>\r\n    </ion-list>\r\n  </ion-content>\r\n</ion-menu>\r\n");
            
            #line 61 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

      }

            
            #line default
            #line hidden
            this.Write("<ion-nav #nav></ion-nav>\r\n");
            
            #line 65 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

    }
    else if (smartApp != null && smartApp.Title != null)
    {

            
            #line default
            #line hidden
            this.Write("<ion-header>\r\n  <ion-navbar>\r\n    <ion-title>\r\n");
            
            #line 73 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

      if (smartApp.Languages.AsEnumerable() != null && smartApp.Languages.AsEnumerable().Count() > 0)
      {

            
            #line default
            #line hidden
            this.Write("      {{ \"applicationTitle\" | translate }}\r\n");
            
            #line 78 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

      }
      else
      {

            
            #line default
            #line hidden
            this.Write("      ");
            
            #line 83 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PascalCase(smartApp.Title)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 84 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

      }

            
            #line default
            #line hidden
            this.Write("    </ion-title>\r\n  </ion-navbar>\r\n</ion-header>\r\n<ion-content padding>\r\n  <p>\r\n");
            
            #line 92 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

      if (smartApp.Languages.AsEnumerable() != null && smartApp.Languages.AsEnumerable().Count() > 0)
      {

            
            #line default
            #line hidden
            this.Write("    Welcome to {{ \"applicationTitle\" | translate }} application !\r\n");
            
            #line 97 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

      }
      else
      {

            
            #line default
            #line hidden
            this.Write("    Welcome to ");
            
            #line 102 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PascalCase(smartApp.Title)));
            
            #line default
            #line hidden
            this.Write(" application !\r\n");
            
            #line 103 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

      }

            
            #line default
            #line hidden
            this.Write("  </p>\r\n</ion-content>\r\n");
            
            #line 108 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\app\AppView.tt"

     }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
