// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 15.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.Ionic
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Language\Templates\LanguageViewTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class LanguageViewTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"
<!--
  You should add your licence here, here is an example :

  SonarQube, open source software quality management tool.
  Copyright (C) 2008-2013 SonarSource
  mailto:contact AT sonarsource DOT com

  SonarQube is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 3 of the License, or (at your option) any later version.
 
  SonarQube is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.
 
  You should have received a copy of the GNU Lesser General Public License
  along with this program; if not, write to the Free Software Foundation,
  Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
-->
<ion-header>
  <ion-navbar>
");
            
            #line 25 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Language\Templates\LanguageViewTemplate.tt"

    if (_isMenu)
    {

            
            #line default
            #line hidden
            this.Write("    <button ion-button icon-only menuToggle>\r\n      <ion-icon name=\"menu\"></ion-i" +
                    "con>\r\n    </button>\r\n");
            
            #line 32 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Language\Templates\LanguageViewTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write(@"    <ion-title text-center>
      {{ ""applicationTitle"" | translate }}
    </ion-title>
    <ion-buttons end>
      <button ion-button icon-only (click)=""onLanguage()"">
        <ion-icon name=""settings""></ion-icon>
      </button>
    </ion-buttons>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <h1>Language preference</h1> 
  <ion-item-group>
");
            
            #line 49 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Language\Templates\LanguageViewTemplate.tt"

    if (_languages.AsEnumerable() != null && _languages.AsEnumerable().Count() > 0)
    {
        foreach (LanguageInfo language in _languages.AsEnumerable()) 
        {
            if (language != null && language.Id != null)
            {

            
            #line default
            #line hidden
            this.Write("    <ion-item (click)=\"changeLanguage(\'");
            
            #line 57 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Language\Templates\LanguageViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PascalCase(language.Id)));
            
            #line default
            #line hidden
            this.Write("\')\">");
            
            #line 57 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Language\Templates\LanguageViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PascalCase(language.Id)));
            
            #line default
            #line hidden
            this.Write("</ion-item>\r\n");
            
            #line 58 "C:\Users\PC\Documents\Gits\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Language\Templates\LanguageViewTemplate.tt"

            }
        }
    }

            
            #line default
            #line hidden
            this.Write("  </ion-item-group>\r\n</ion-content>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
