// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 16.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.Ionic
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class LayoutModuleTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"
/*
 * You should add your licence here, here is an example :
 *
 * SonarQube, open source software quality management tool.
 * Copyright (C) 2008-2013 SonarSource
 * mailto:contact AT sonarsource DOT com
 *
 * SonarQube is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * SonarQube is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
");
            
            #line 23 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

    if (ConcernId != null
        && Layout != null
        && Layout.Id != null)
    {
        var layout = $"{ConcernId.ToPascalCase()}{Layout.Id.ToPascalCase()}";
        var layoutToLower = $"{ConcernId.ToCamelCase()}-{Layout.Id.ToCamelCase()}";

            
            #line default
            #line hidden
            this.Write("import { NgModule } from \'@angular/core\';\r\nimport { IonicPageModule } from \'ionic" +
                    "-angular\';\r\n\r\nimport { ");
            
            #line 34 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(layout));
            
            #line default
            #line hidden
            this.Write(" } from \'./");
            
            #line 34 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(layoutToLower));
            
            #line default
            #line hidden
            this.Write("\';\r\n");
            
            #line 35 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

        if (Languages.AsEnumerable() != null
            && Languages.AsEnumerable().Count() > 0)
        {

            
            #line default
            #line hidden
            this.Write("import { TranslateModule } from \'@ngx-translate/core\';\r\n");
            
            #line 41 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

        }

        if (ApiDomainServices.AsEnumerable() != null
            && ApiDomainServices.AsEnumerable().Count() > 0)
        {
            foreach (var service in ApiDomainServices.AsEnumerable())
            {

            
            #line default
            #line hidden
            this.Write("import { ");
            
            #line 50 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" } from \'../../../services/");
            
            #line 50 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".service\';\r\n");
            
            #line 51 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

            }
        }

            
            #line default
            #line hidden
            this.Write("\r\n/**\r\n * class: ");
            
            #line 57 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(layout));
            
            #line default
            #line hidden
            this.Write("PageModule.\r\n");
            
            #line 58 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

        if (Layout.Description != null)
        {

            
            #line default
            #line hidden
            this.Write(" * ");
            
            #line 62 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Layout.Description));
            
            #line default
            #line hidden
            this.Write(".\r\n * This is the module of the current layout.\r\n * This module is generated from" +
                    " Concerns domain.\r\n */\r\n");
            
            #line 66 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write(" * You should add a description of your\r\n * layout\'s module here.\r\n * This is the" +
                    " module of the current layout.\r\n * This module is generated from Concerns domain" +
                    ".\r\n */\r\n");
            
            #line 76 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("@NgModule({\r\n  declarations: [\r\n    ");
            
            #line 81 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(layout));
            
            #line default
            #line hidden
            this.Write("\r\n  ],\r\n  imports: [\r\n");
            
            #line 84 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

        if (Languages.AsEnumerable() != null
            && Languages.AsEnumerable().Count() > 0)
        {

            
            #line default
            #line hidden
            this.Write("    TranslateModule.forChild(),\r\n");
            
            #line 90 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("    IonicPageModule.forChild(");
            
            #line 93 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(layout));
            
            #line default
            #line hidden
            this.Write(")\r\n  ],\r\n  providers: [\r\n");
            
            #line 96 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

        if (ApiDomainServices.AsEnumerable() != null
            && ApiDomainServices.AsEnumerable().Count() > 0)
        {
            var lastIndex = ApiDomainServices.AsEnumerable().Count() - 1;
            var index = 0;

            foreach (var service in ApiDomainServices.AsEnumerable())
            {
                if (index == lastIndex)
                {

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 108 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 109 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

                }
                else
                {

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 114 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 115 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

                }
                index++;
            }
        }

            
            #line default
            #line hidden
            this.Write("  ]\r\n})\r\nexport class ");
            
            #line 123 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(layout));
            
            #line default
            #line hidden
            this.Write("PageModule {}\r\n");
            
            #line 124 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\Layout\Templates\LayoutModuleTemplate.tt"

    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
