// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.Ionic
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsModule.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TabsModule : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsModule.tt"

    var model = (SmartAppInfo)Model;

            
            #line default
            #line hidden
            this.Write(@"import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Routes, RouterModule } from '@angular/router';
import { IonicModule } from '@ionic/angular';

import { AppTabsPage } from './app-tabs.page';
import { AuthorizationGuard } from '../../core/services/authorization.guard';

const routes: Routes = [
    {
        path: '',
        component: AppTabsPage,
        children: [
        {
            path: '',
            redirectTo: '/tabs/");
            
            #line 21 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsModule.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_rootScreen));
            
            #line default
            #line hidden
            this.Write("\',\r\n            pathMatch: \'full\'\r\n        },\r\n        {\r\n            path: \'apps" +
                    "ettings\',\r\n            loadChildren: \'../appsettings/app-settings.module#AppSett" +
                    "ingsPageModule\',\r\n        },\r\n");
            
            #line 28 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsModule.tt"

    foreach(var concern in model.Concerns)
     {

            
            #line default
            #line hidden
            this.Write("        {\r\n            path: \'");
            
            #line 33 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsModule.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concern.Id.ToLower()));
            
            #line default
            #line hidden
            this.Write("\',\r\n            loadChildren: \'../");
            
            #line 34 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsModule.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concern.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 34 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsModule.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concern.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".module#");
            
            #line 34 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsModule.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concern.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("PageModule\',\r\n            //canActivate: [AuthorizationGuard]\r\n        },\r\n");
            
            #line 37 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsModule.tt"

     }

            
            #line default
            #line hidden
            this.Write("        ]\r\n    }\r\n];\r\n\r\n@NgModule({\r\n  imports: [\r\n    CommonModule,\r\n    FormsMo" +
                    "dule,\r\n    IonicModule,\r\n    RouterModule.forChild(routes)\r\n  ],\r\n  declarations" +
                    ": [AppTabsPage]\r\n})\r\n\r\nexport class AppTabsPageModule {}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
