// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.Ionic
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsPageView.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TabsPageView : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsPageView.tt"

    var model = (SmartAppInfo)Model;

            
            #line default
            #line hidden
            this.Write("<ion-tabs>\r\n    <ion-tab-bar slot=\"bottom\">\r\n        <ion-tab-button tab=\"");
            
            #line 7 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsPageView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_rootScreen));
            
            #line default
            #line hidden
            this.Write("\">\r\n            <ion-icon name=\"logo-ionic\"></ion-icon>\r\n            <ion-label>");
            
            #line 9 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsPageView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_rootScreen.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("</ion-label>\r\n        </ion-tab-button>\r\n");
            
            #line 11 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsPageView.tt"

    foreach(var concern in model.Concerns)
     {
         if(concern.Id.ToLower() != _rootScreen){

            
            #line default
            #line hidden
            this.Write("        <ion-tab-button tab=\"");
            
            #line 16 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsPageView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concern.Id.ToLower()));
            
            #line default
            #line hidden
            this.Write("\">\r\n            <ion-icon name=\"logo-ionic\"></ion-icon>\r\n            <ion-label>");
            
            #line 18 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsPageView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concern.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("</ion-label>\r\n        </ion-tab-button>\r\n");
            
            #line 20 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Pages\Templates\Tabs\TabsPageView.tt"

            }
     }

            
            #line default
            #line hidden
            this.Write("        <ion-tab-button tab=\"appsettings\">\r\n            <ion-icon name=\"settings\"" +
                    "></ion-icon>\r\n            <ion-label>Settings</ion-label>\r\n        </ion-tab-but" +
                    "ton>\r\n    </ion-tab-bar>\r\n</ion-tabs>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
