// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.Ionic
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ViewModelTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import { BaseViewModel } from \'./baseViewModel\';\r\n");
            
            #line 3 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"

    var model = (EntityInfo)Model;

            
            #line default
            #line hidden
            
            #line 6 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"

    if(_dataModel != null && _dataModel.Id != null)
    {
        if(_constructorParametersObj.AsEnumerable() != null && _constructorParametersObj.AsEnumerable().Count() > 0 )
        {
            foreach(var property in _constructorParametersObj.AsEnumerable())
            {
                if (property.Target != null && property.Type != null)
                {

            
            #line default
            #line hidden
            this.Write("import { ");
            
            #line 16 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 16 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelSuffix.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" } from \'../shared/models/");
            
            #line 16 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 16 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelSuffix.ToLower()));
            
            #line default
            #line hidden
            this.Write("\';\r\n");
            
            #line 17 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"

                }
            }
        }

            
            #line default
            #line hidden
            this.Write("\r\n/**\r\n * class: ");
            
            #line 24 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_dataModel.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("\r\n * You should add a description of your entity here.\r\n * This viewModel is a re" +
                    "ference used in Concerns or\r\n * in APIs\' parameters or return types.\r\n * This mo" +
                    "del is generated from ViewModel domain.\r\n */\r\n\r\nexport interface  ");
            
            #line 31 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_dataModel.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" extends BaseViewModel {\r\n\r\n");
            
            #line 33 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"

    if(_constructorParametersObj.AsEnumerable() != null && _constructorParametersObj.AsEnumerable().Count() > 0 )
    {
        foreach(var property in _constructorParametersObj.AsEnumerable())
        {	

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 39 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 39 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TypeScriptType()));
            
            #line default
            #line hidden
            
            #line 39 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
if(Helper.IsModelBool(property.Type)){
            
            #line default
            #line hidden
            
            #line 39 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelSuffix));
            
            #line default
            #line hidden
            
            #line 39 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 39 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
if(property.IsCollection){
            
            #line default
            #line hidden
            this.Write("[]");
            
            #line 39 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 40 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 45 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\ViewModel\Templates\ViewModelTemplate.tt"

    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
