// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 16.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.Ionic
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ApiTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"
/*
 * You should add your licence here, here is an example :
 *
 * SonarQube, open source software quality management tool.
 * Copyright (C) 2008-2013 SonarSource
 * mailto:contact AT sonarsource DOT com
 *
 * SonarQube is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * SonarQube is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

");
            
            #line 26 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

    if (ViewModels.AsEnumerable() != null)
    {
        foreach(var viewModel in ViewModels.AsEnumerable())
        {

            
            #line default
            #line hidden
            this.Write("import { ");
            
            #line 32 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" } from \'../viewModels/");
            
            #line 32 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\';\r\n");
            
            #line 33 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\r\nimport { DataService } from \'./data.service\';\r\n\r\n");
            
            #line 40 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

    if (Api.Id != null)
    {

            
            #line default
            #line hidden
            this.Write("/**\r\n * class: ");
            
            #line 45 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Api.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 46 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

        if (Api.Description != null)
        {

            
            #line default
            #line hidden
            this.Write(" * ");
            
            #line 50 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Api.Description));
            
            #line default
            #line hidden
            this.Write(".\r\n * This service is generated from API domain.\r\n");
            
            #line 52 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write(" * You should add a description of your service here.\r\n * This service is generat" +
                    "ed from API domain.\r\n");
            
            #line 59 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write(" */\r\n@Injectable()\r\nexport class ");
            
            #line 64 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Api.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 65 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

        if (Api.Actions.AsEnumerable() != null)
        {
            foreach (var action in Api.Actions.AsEnumerable())
            {
                if (action.Id != null
                    && action.Url != null)
                {

            
            #line default
            #line hidden
            this.Write("  public _");
            
            #line 74 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Api = \'");
            
            #line 74 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Url));
            
            #line default
            #line hidden
            this.Write("\';\r\n");
            
            #line 75 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                }
            }
        }

            
            #line default
            #line hidden
            this.Write("  constructor(public _dataService: DataService){}\r\n");
            
            #line 81 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

        if (Api.Actions.AsEnumerable() != null)
        {
            foreach (var action in Api.Actions.AsEnumerable())
            {
                if (action.Id != null
                    && action.Url != null
                    && action.Type != null)
                {

            
            #line default
            #line hidden
            this.Write("    /**\r\n     * method: ");
            
            #line 92 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".\r\n     * You should add a description of your method here.\r\n     * That method s" +
                    "hould be used to connect with generated\r\n     * backend API. You should add busi" +
                    "ness logic inside.\r\n");
            
            #line 96 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                    if (action.Parameters.AsEnumerable() != null
                        && action.Parameters.AsEnumerable().Count() > 0)
                    {
                        foreach (var apiParameter in action.Parameters.AsEnumerable())
                        {
                            if (apiParameter.Id != null)
                            {
                                var type = apiParameter.TypeScriptType();

            
            #line default
            #line hidden
            this.Write("     * @param ");
            
            #line 106 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Param `");
            
            #line 106 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type));
            
            #line default
            #line hidden
            this.Write("`.\r\n");
            
            #line 107 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            }
                        }
                    }
                    if (action.ReturnType != null
                        && action.ReturnType.Id != null)
                    {

            
            #line default
            #line hidden
            this.Write("     * @returns `");
            
            #line 115 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.ReturnType.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(">`.\r\n");
            
            #line 116 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                    }

            
            #line default
            #line hidden
            this.Write("     */\r\n    public ");
            
            #line 120 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(\r\n");
            
            #line 121 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                    if (action.Parameters.AsEnumerable() != null
                        && action.Parameters.AsEnumerable().Count() > 0)
                    {
                        var last = action.Parameters.AsEnumerable().Last();

                        foreach (var apiParameter in action.Parameters.AsEnumerable())
                        {
                            if (apiParameter.Id != null)
                            {
                                var type = apiParameter.TypeScriptType();

                                if (apiParameter.Equals(last))
                                {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 136 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Param: ");
            
            #line 136 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 137 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                }
                                else
                                {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 142 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Param: ");
            
            #line 142 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 143 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                }
                            }
                        }
                    }

                    if (action.ReturnType != null
                        && action.ReturnType.Id != null)
                    {

            
            #line default
            #line hidden
            this.Write("    ): Observable<");
            
            #line 153 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.ReturnType.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("> {\r\n");
            
            #line 154 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                    }
                    else
                    {

            
            #line default
            #line hidden
            this.Write("    ) {\r\n");
            
            #line 160 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                    }

                    switch (action.Type)
                    {
                        case "dataget": case "datalist":

            
            #line default
            #line hidden
            this.Write("        return this._dataService.get(\r\n");
            
            #line 168 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            if (action.Parameters.AsEnumerable() != null
                                && action.Parameters.AsEnumerable().Count() > 0)
                            {

            
            #line default
            #line hidden
            this.Write("          `${this._");
            
            #line 173 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Api}`,\r\n          {\r\n");
            
            #line 175 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                var last = action.Parameters.AsEnumerable().Last();

                                foreach (var apiParameter in action.Parameters.AsEnumerable())
                                {
                                    if (apiParameter.Id != null)
                                    {
                                        if (apiParameter.Equals(last))
                                        {

            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 185 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": JSON.stringify(");
            
            #line 185 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Param)\r\n");
            
            #line 186 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                        }
                                        else
                                        {

            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 191 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": JSON.stringify(");
            
            #line 191 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Param),\r\n");
            
            #line 192 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                        }
                                    }
                                }

            
            #line default
            #line hidden
            this.Write("          });\r\n");
            
            #line 198 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            }
                            else
                            {

            
            #line default
            #line hidden
            this.Write("          `${this._");
            
            #line 203 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Api}`,\r\n          {});\r\n");
            
            #line 205 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            }

                        break;
                        case "datacreate": 

            
            #line default
            #line hidden
            this.Write("        return this._dataService.post(\r\n");
            
            #line 212 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            if (action.Parameters.AsEnumerable() != null
                                && action.Parameters.AsEnumerable().Count() > 0)
                            {

            
            #line default
            #line hidden
            this.Write("          `${this._");
            
            #line 217 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Api}`,\r\n          {\r\n");
            
            #line 219 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                var last = action.Parameters.AsEnumerable().Last();

                                foreach (var apiParameter in action.Parameters.AsEnumerable())
                                {
                                    if (apiParameter.Id != null)
                                    {
                                        if (apiParameter.Equals(last))
                                        {

            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 229 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 229 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Param\r\n");
            
            #line 230 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                        }
                                        else
                                        {

            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 235 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 235 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Param,\r\n");
            
            #line 236 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                        }
                                    }
                                }

            
            #line default
            #line hidden
            this.Write("          },\r\n         {});\r\n");
            
            #line 243 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            }
                            else
                            {

            
            #line default
            #line hidden
            this.Write("          `${this._");
            
            #line 248 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Api}`,\r\n          {},\r\n          {});\r\n");
            
            #line 251 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            }

                        break;
                        case "dataupdate":

            
            #line default
            #line hidden
            this.Write("        return this._dataService.put(\r\n");
            
            #line 258 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            if (action.Parameters.AsEnumerable() != null
                                && action.Parameters.AsEnumerable().Count() > 0)
                            {

            
            #line default
            #line hidden
            this.Write("          `${this._");
            
            #line 263 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Api}`,\r\n          {\r\n");
            
            #line 265 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                var last = action.Parameters.AsEnumerable().Last();

                                foreach (var apiParameter in action.Parameters.AsEnumerable())
                                {
                                    if (apiParameter.Id != null)
                                    {
                                        if (apiParameter.Equals(last))
                                        {

            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 275 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 275 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Param\r\n");
            
            #line 276 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                        }
                                        else
                                        {

            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 281 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 281 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Param,\r\n");
            
            #line 282 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                        }
                                    }
                                }

            
            #line default
            #line hidden
            this.Write("          },\r\n         {});\r\n");
            
            #line 289 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            }
                            else
                            {

            
            #line default
            #line hidden
            this.Write("            `${this._");
            
            #line 294 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Api}`,\r\n            {},\r\n            {});\r\n");
            
            #line 297 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            }

                        break;
                        case "datadelete":

            
            #line default
            #line hidden
            this.Write("        return this._dataService.delete(\r\n");
            
            #line 304 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            if (action.Parameters.AsEnumerable() != null
                                && action.Parameters.AsEnumerable().Count() > 0)
                            {

            
            #line default
            #line hidden
            this.Write("            `${this._");
            
            #line 309 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Api}`,\r\n            {\r\n");
            
            #line 311 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                var last = action.Parameters.AsEnumerable().Last();

                                foreach (var apiParameter in action.Parameters.AsEnumerable())
                                {
                                    if (apiParameter.Id != null)
                                    {
                                        if (apiParameter.Equals(last))
                                        {

            
            #line default
            #line hidden
            this.Write("               ");
            
            #line 321 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": JSON.stringify(");
            
            #line 321 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Param)\r\n");
            
            #line 322 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
	
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
            this.Write("               ");
            
            #line 327 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": JSON.stringify(");
            
            #line 327 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Param),\r\n");
            
            #line 328 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                                        }
                                    }
                                }

            
            #line default
            #line hidden
            this.Write("            });\r\n");
            
            #line 334 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            }
                            else
                            {

            
            #line default
            #line hidden
            this.Write("            `${this._");
            
            #line 339 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Api}`,\r\n            {});\r\n");
            
            #line 341 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                            }

                        break;
                        default: break;
                    }

            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 349 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

                }
            }
        }

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 355 "C:\Users\PC\Documents\Gits\Ionic-framework\GeneratorProject.IonicFrameworkCodeSamples\GeneratorProject\Platforms\Frontend\Ionic\API\Templates\ApiTemplate.tt"

    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
