// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.Ionic
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Shared\Templates\Services\AuthClient\OidcConfigurationService.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class OidcConfigurationService : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"import {Injectable} from '@angular/core';
import {UserManagerSettings} from 'oidc-client';
import {BehaviorSubject} from 'rxjs';
import {filter} from 'rxjs/operators';

@Injectable()
export class OidcConfigurationService {
  authSettings: UserManagerSettings = {};

  constructor() {
  }

  _loaded$: BehaviorSubject<boolean> = new BehaviorSubject(false);

  get loaded$() {
    return this._loaded$.asObservable().pipe(filter(_ => _));
  }

  setSettings(_settings: any) {
    if (!_settings.clientRoot) {
      throw new Error('client root url missing in configuration');
    }

    if (!_settings.client_id) {
      throw new Error('client id missing in configuration');
    }

    const clientRoot = _settings.clientRoot.replace(/^\/|\/$/g, '');
    delete _settings.clientRoot;
    const settings = {
      ..._settings,
      client_id: _settings.client_id,
      redirect_uri: `${clientRoot}/account/auth-callback`,
      post_logout_redirect_uri: `${clientRoot}/account/postLogout`,
    };

    this.authSettings = {
      ...this.authSettings,
      ...settings,
    };

    this._loaded$.next(true);
  }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
