// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.Ionic
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\New folder\IonicGenerator\IonicGenerator\GeneratorProject\Platforms\Frontend\Ionic\Common\Templates\src\themes\Variables.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Variables : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// Ionic Variables and Theming. For more info, please see:\r\n// http://ionicframew" +
                    "ork.com/docs/theming/\r\n\r\n/** Ionic CSS Variables **/\r\n:root {\r\n  /** primary **/" +
                    "\r\n  --ion-color-primary: #3880ff;\r\n  --ion-color-primary-rgb: 56, 128, 255;\r\n  -" +
                    "-ion-color-primary-contrast: #ffffff;\r\n  --ion-color-primary-contrast-rgb: 255, " +
                    "255, 255;\r\n  --ion-color-primary-shade: #3171e0;\r\n  --ion-color-primary-tint: #4" +
                    "c8dff;\r\n\r\n  /** secondary **/\r\n  --ion-color-secondary: #0cd1e8;\r\n  --ion-color-" +
                    "secondary-rgb: 12, 209, 232;\r\n  --ion-color-secondary-contrast: #ffffff;\r\n  --io" +
                    "n-color-secondary-contrast-rgb: 255, 255, 255;\r\n  --ion-color-secondary-shade: #" +
                    "0bb8cc;\r\n  --ion-color-secondary-tint: #24d6ea;\r\n\r\n  /** tertiary **/\r\n  --ion-c" +
                    "olor-tertiary: #7044ff;\r\n  --ion-color-tertiary-rgb: 112, 68, 255;\r\n  --ion-colo" +
                    "r-tertiary-contrast: #ffffff;\r\n  --ion-color-tertiary-contrast-rgb: 255, 255, 25" +
                    "5;\r\n  --ion-color-tertiary-shade: #633ce0;\r\n  --ion-color-tertiary-tint: #7e57ff" +
                    ";\r\n\r\n  /** success **/\r\n  --ion-color-success: #10dc60;\r\n  --ion-color-success-r" +
                    "gb: 16, 220, 96;\r\n  --ion-color-success-contrast: #ffffff;\r\n  --ion-color-succes" +
                    "s-contrast-rgb: 255, 255, 255;\r\n  --ion-color-success-shade: #0ec254;\r\n  --ion-c" +
                    "olor-success-tint: #28e070;\r\n\r\n  /** warning **/\r\n  --ion-color-warning: #ffce00" +
                    ";\r\n  --ion-color-warning-rgb: 255, 206, 0;\r\n  --ion-color-warning-contrast: #fff" +
                    "fff;\r\n  --ion-color-warning-contrast-rgb: 255, 255, 255;\r\n  --ion-color-warning-" +
                    "shade: #e0b500;\r\n  --ion-color-warning-tint: #ffd31a;\r\n\r\n  /** danger **/\r\n  --i" +
                    "on-color-danger: #f04141;\r\n  --ion-color-danger-rgb: 245, 61, 61;\r\n  --ion-color" +
                    "-danger-contrast: #ffffff;\r\n  --ion-color-danger-contrast-rgb: 255, 255, 255;\r\n " +
                    " --ion-color-danger-shade: #d33939;\r\n  --ion-color-danger-tint: #f25454;\r\n\r\n  /*" +
                    "* dark **/\r\n  --ion-color-dark: #222428;\r\n  --ion-color-dark-rgb: 34, 34, 34;\r\n " +
                    " --ion-color-dark-contrast: #ffffff;\r\n  --ion-color-dark-contrast-rgb: 255, 255," +
                    " 255;\r\n  --ion-color-dark-shade: #1e2023;\r\n  --ion-color-dark-tint: #383a3e;\r\n\r\n" +
                    "  /** medium **/\r\n  --ion-color-medium: #989aa2;\r\n  --ion-color-medium-rgb: 152," +
                    " 154, 162;\r\n  --ion-color-medium-contrast: #ffffff;\r\n  --ion-color-medium-contra" +
                    "st-rgb: 255, 255, 255;\r\n  --ion-color-medium-shade: #86888f;\r\n  --ion-color-medi" +
                    "um-tint: #a2a4ab;\r\n\r\n  /** light **/\r\n  --ion-color-light: #f4f5f8;\r\n  --ion-col" +
                    "or-light-rgb: 244, 244, 244;\r\n  --ion-color-light-contrast: #000000;\r\n  --ion-co" +
                    "lor-light-contrast-rgb: 0, 0, 0;\r\n  --ion-color-light-shade: #d7d8da;\r\n  --ion-c" +
                    "olor-light-tint: #f5f6f9;\r\n}\r\n\r\n\r\n.light-theme{\r\n    --ion-background-color: #ff" +
                    "ffff;\r\n    --ion-background-color-rgb: 255,255,255;\r\n  \r\n    --ion-text-color: #" +
                    "000000;\r\n    --ion-text-color-rgb: 0,0,0;\r\n  \r\n    --ion-color-step-50: #f2f2f2;" +
                    "\r\n    --ion-color-step-100: #e6e6e6;\r\n    --ion-color-step-150: #d9d9d9;\r\n    --" +
                    "ion-color-step-200: #cccccc;\r\n    --ion-color-step-250: #bfbfbf;\r\n    --ion-colo" +
                    "r-step-300: #b3b3b3;\r\n    --ion-color-step-350: #a6a6a6;\r\n    --ion-color-step-4" +
                    "00: #999999;\r\n    --ion-color-step-450: #8c8c8c;\r\n    --ion-color-step-500: #808" +
                    "080;\r\n    --ion-color-step-550: #737373;\r\n    --ion-color-step-600: #666666;\r\n  " +
                    "  --ion-color-step-650: #595959;\r\n    --ion-color-step-700: #4d4d4d;\r\n    --ion-" +
                    "color-step-750: #404040;\r\n    --ion-color-step-800: #333333;\r\n    --ion-color-st" +
                    "ep-850: #262626;\r\n    --ion-color-step-900: #191919;\r\n    --ion-color-step-950: " +
                    "#0d0d0d;\r\n}\r\n\r\n.dark-theme{\r\n  --ion-background-color: #000000;\r\n  --ion-backgro" +
                    "und-color-rgb: 0,0,0;\r\n\r\n  --ion-text-color: #ffffff;\r\n  --ion-text-color-rgb: 2" +
                    "55,255,255;\r\n\r\n  --ion-color-step-50: #0d0d0d;\r\n  --ion-color-step-100: #1a1a1a;" +
                    "\r\n  --ion-color-step-150: #262626;\r\n  --ion-color-step-200: #333333;\r\n  --ion-co" +
                    "lor-step-250: #404040;\r\n  --ion-color-step-300: #4d4d4d;\r\n  --ion-color-step-350" +
                    ": #595959;\r\n  --ion-color-step-400: #666666;\r\n  --ion-color-step-450: #737373;\r\n" +
                    "  --ion-color-step-500: #808080;\r\n  --ion-color-step-550: #8c8c8c;\r\n  --ion-colo" +
                    "r-step-600: #999999;\r\n  --ion-color-step-650: #a6a6a6;\r\n  --ion-color-step-700: " +
                    "#b3b3b3;\r\n  --ion-color-step-750: #bfbfbf;\r\n  --ion-color-step-800: #cccccc;\r\n  " +
                    "--ion-color-step-850: #d9d9d9;\r\n  --ion-color-step-900: #e6e6e6;\r\n  --ion-color-" +
                    "step-950: #f2f2f2;\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
